class TaskNotDoneException(Exception):
    "Raised when a task is found unsuccessful"
    pass